services:
  backend:
    build:
      dockerfile: Dockerfile.dev
      network: host
    volumes:
      - ./run/dev:/data
      - ./src:/usr/src/app/src
      - ./public:/usr/src/app/public
    ports:
      - 3000:3000
    security_opt:
      - apparmor:unconfined