# use the official Bun image
# see all versions at https://hub.docker.com/r/oven/bun/tags
FROM oven/bun:1
WORKDIR /usr/src/app
COPY package.json bun.lock .
RUN mkdir -p /data/db

RUN bun install

ENV NODE_ENV=development

# run the app
ENTRYPOINT [ "bun", "--watch", "run", "src/index.ts" ]