CREATE TABLE IF NOT EXISTS threads(
    id INTEGER PRIMARY KEY AUTOINCREMENT
);

INSERT INTO threads(id) VALUES(1);

ALTER TABLE posts
    ADD COLUMN thread INT NOT NULL DEFAULT 1 REFERENCES threads(id);
ALTER TABLE posts
    ADD COLUMN reply_to INT REFERENCES posts(id);